name: CI
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ["**"]

jobs:
  test:
    name: Run tests and linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/library/golang:1.20.1@sha256:52921e63cc544c79c111db1d8461d8ab9070992d9c636e1573176642690c14b5
        name: Run unit tests
        with:
          entrypoint: go
          args: test -v ./...
      - uses: docker://docker.io/library/golang:1.20.1@sha256:52921e63cc544c79c111db1d8461d8ab9070992d9c636e1573176642690c14b5
        name: Run go vet
        with:
          entrypoint: go
          args: vet ./...
  build:
    needs: test
    name: Build the binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        GOOS: [linux, darwin]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/library/golang:1.20.1@sha256:52921e63cc544c79c111db1d8461d8ab9070992d9c636e1573176642690c14b5
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        with:
          entrypoint: go
          args: build
      - uses: actions/upload-artifact@v2
        with:
          name: mock-hubble-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: mock-hubble

